apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ssc-skaffold
build:
  platforms:
    - linux/amd64
  artifacts:
    - image: gcr.io/four-track-friday-2/watch_hawthorne_stereo
      hooks:
        before:
          - command: [ "./bin/sbt", "clean", "dist" ]
        after:
          - command: [ "./bin/sbt", "clean" ]
      context: .
      docker:
        dockerfile: src/docker/Dockerfile
        buildArgs:
          SERVICE_VERSION: "0.1.0-SNAPSHOT"
  tagPolicy:
    gitCommit: {}
  local: {}
test:
  - image: gcr.io/four-track-friday-2/watch_hawthorne_stereo
    structureTests:
      - ./src/test/container-structure/test_commands.yml
      - ./src/test/container-structure/test_metadata.yml
deploy: {}
# no custom profiles here
# this skaffold config stops at pushing the docker image to the registry
